# core.py
print("🧠 Bienvenido a Builder OS")
print("Selecciona un módulo para iniciar:")
print("1. Builder Mode")
print("2. Net")
print("3. Visual")
print("4. Scripts")
print("5. Prometeo")
print("6. Argos")
print("7. Crypto")
print("8. Convergence")
print("9. Awakener")