services:
  - type: web
    name: arkaios-gateway-open
    env: node
    plan: free
    region: oregon

    # 👇 muy importante: Render hará build/start dentro de esta carpeta
    rootDir: arkaios_gateway/server

    buildCommand: npm ci --omit=dev
    startCommand: node min.js
    healthCheckPath: /aida/health
    autoDeploy: true

    envVars:
      - key: RENDER_NODE_VERSION
        value: "20"
      - key: OPEN_MODE
        value: "1"
      - key: RATE_LIMIT
        value: "0"
      - key: ALLOW_ORIGIN
        value: "https://djklmr2025.github.io"
