version: 1

services:
  - type: web
    name: arkaios-gateway-open
    env: node
    plan: free
    region: oregon
    rootDir: arkaios_gateway/server
    buildCommand: npm install
    startCommand: node gateway.js
    healthCheckPath: /aida/health
    autoDeploy: true

    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: OPEN_MODE
        value: "1"
      - key: BRIDGE_ALLOW
        value: "Puter,Copilot,Gemini,ARKAIOS"