services:
  - type: web
    name: arkaios-gateway
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node arkaios_gateway/server/gateway.js
    envVars:
      - key: PORT
        value: 8080
      - key: SECRET_MASTER_TOKEN
        value: changeme
      - key: UNIQUE_PATH_TOKEN
        value: arkaios-secret
      - key: OPEN_MODE
        value: "1"
      - key: PUBLIC_ACTIONS
        value: echo,plan,analyze,explain,generate
      - key: ALLOW_ORIGIN
        value: "*"