version: 1

services:
  - type: web
    name: arkaios-gateway-open
    env: node
    plan: free
    region: oregon
    rootDir: arkaios_gateway/server
    buildCommand: cd arkaios_gateway/server && npm i
    startCommand: cd arkaios_gateway/server && node gateway.js
    healthCheckPath: /aida/health
    autoDeploy: true

    envVars:
      - key: NODE_VERSION
        value: "20"

      - key: OPEN_MODE
        value: "0"

      - key: PUBLIC_ACTIONS
        value: "echo,plan,analyze,explain,generate"

      - key: ALLOW_ORIGIN
        value: "https://djklmr2025.github.io"

      - key: SECRET_BASE
        value: "/arkaios/secure"

      - key: TRUST_PROXY
        value: "1"

      - key: LOG_LEVEL
        value: "info"

      - key: MASTER_TOKEN
        sync: false
        value: "******"