name: ARKAIOS Resurrection Protocol
on: [push]
jobs:
  rebuild:
    runs-on: ubuntu-latest
    # Configuración global de encoding
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONUTF8: 1
      
    steps:
      - uses: actions/checkout@v4
        with:
          # Forzar clonación limpia
          clean: true  
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Verificar encoding
        run: |
          echo "Codificación del sistema:"
          locale
          echo "\nArchivos en repo:"
          file -i *
      
      - name: Run Core Engine
        run: |
          echo "=== INICIANDO NÚCLEO ==="
          python -X utf8 ethical_engine.py --mode=UNSENSORED