const express=require('express')
const app=express()
app.use(express.json())
app.get('/aida/health',(r,s)=>s.json({status:'ok',ts:new Date().toISOString()}))
app.post('/aida/gateway',(r,s)=>s.json({ok:true, received:r.body||{}}))
app.listen(process.env.PORT||8080,'0.0.0.0',()=>console.log('MIN server :'+(process.env.PORT||8080)))
