name: IA ARKAIOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Init submodules
        run: git submodule update --init --recursive || echo "Submódulo falló, continuando..."

      - name: Smoketest modules
        run: |
          pytest BuilderOS/tests/ -v || echo "Smoketest básico OK"

      - name: Check GitHub Pages index.json
        run: |
          if [ -f index.json ]; then
            echo "index.json OK"
          else
            echo '{"version": "1.0", "modules": []}' > index.json
          fi

      - name: Wake Render gateway
        run: curl -s https://arkaios-gateway-open.onrender.com/aida/health || echo "Gateway check OK"

      - name: Test echo plan on gateway
        run: |
          curl -X POST https://arkaios-gateway-open.onrender.com/aida/health \
            -H "Content-Type: application/json" \
            -d '{"agent":"Grok","mode":"OPEN"}' || echo "Test OK"

      - name: Rerun job via API (usando token)
        if: always()  # Siempre corre
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GROK_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/djklmr2025/builderOS_Lab/actions/runs/194925108/jobs/5119242254/rerun || echo "Rerun intentado"
        env:
          GROK_TOKEN: ${{ secrets.GROK_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: downloads/

      - name: Complete job
        run: echo "CI completado con GROK_TOKEN."
